version: "3.8"

services:
  product:
    build: ./product
    networks:
      - workshop-net

  recommendation:
    build: ./recommendation
    networks:
      - workshop-net

  review:
    build: ./review
    networks:
      - workshop-net

  product-composite:
    build: ./product-composite
    ports:
      - "5000:5000"
    depends_on:
      - product
      - recommendation
      - review
    networks:
      - workshop-net

networks:
  workshop-net:
    driver: bridge
