# k8s/recommendation-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: workshop
spec:
  selector:
    app: recommendation
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
