apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 9376
      port: 80
      nodePort: 30080
  selector:
    app: myapp
    type: front-end
