apiVersion: v1
kind: Pod
metadata:
  name: api-server
  namespace: monitoring-demo
  labels:
    app: api-server
spec:
  containers:
  - name: api-server
    image: nagabhushanamn/api-server:v1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: monitoring-demo
spec:
  selector:
    app: api-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
