apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring-demo
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag         kube.*
    [OUTPUT]
        Name         es
        Match        kube.*
        Host         elasticsearch.monitoring-demo.svc.cluster.local
        Port         9200
        Logstash_Format On
