apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: monitoring-demo
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    - name: MYSQL_DATABASE
      value: "mydb"
    - name: MYSQL_USER
      value: "user"
    - name: MYSQL_PASSWORD
      value: "password"
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-init
      mountPath: /docker-entrypoint-initdb.d  # MySQL executes .sql files from here
  volumes:
  - name: mysql-init
    configMap:
      name: mysql-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: monitoring-demo
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
