apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: monitoring-demo
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;

    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL
    );

    INSERT INTO users (name, email) VALUES
    ('Alice Johnson', 'alice@example.com'),
    ('Bob Smith', 'bob@example.com'),
    ('Charlie Brown', 'charlie@example.com');
