apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: monitoring-demo
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/conf.d/
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config  # Mount the ConfigMap
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: monitoring-demo
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
