apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: monitoring-demo
data:
  default.conf: |
    server {
        listen 80;

        location /api/ {
            rewrite ^/api/(.*) /$1 break;  # Remove "/api/" before passing to API server
            proxy_pass http://api-server.monitoring-demo.svc.cluster.local:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
