apiVersion: v1
kind: Pod
metadata:
  name: rq-count-2
spec:
  containers:
    - name: rq-count
      image: nagabhushanamn/req-count-service
      volumeMounts:
        - mountPath: /app/data
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: pvc-example

