apiVersion: v1
kind: Pod
metadata:
  name: req-count-2
spec:
  nodeName: kind-cluster-worker2
  containers:
    - name: req-count
      image: nagabhushanamn/req-count-service
      volumeMounts:
        - mountPath: /app/data
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: req-count-pvc

