apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
    matchExpressions:
      - key: type
        operator: In
        values:
          - front-end  
          - fe
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
      - image: nginx
        name: nginx-container
