# k8s/mongodb-product-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb-product
  namespace: workshop
spec:
  selector:
    app: mongodb-product
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
