# k8s/mongodb-product-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-product
  namespace: workshop
  labels:
    app: mongodb-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-product
  template:
    metadata:
      labels:
        app: mongodb-product
    spec:
      containers:
        - name: mongodb-product
          image: mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-product-storage
      volumes:
        - name: mongo-product-storage
          emptyDir: {}
