apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: workshop
  labels:
    app: product
spec:
  replicas: 3 # Increased from 1 to 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: nagabhushanamn/product:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-product:27017/productdb"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
