# k8s/product-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: workshop
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
