apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: workshop
  labels:
    app: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: nagabhushanamn/product:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCT_SERVICE_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
            - name: FEATURE_FLAG
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FEATURE_FLAG
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JWT_SECRET_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
